name = "strava-heatmap-proxy"
type = "webpack"

# Change this to your own account ID
account_id = "32100188be477c016941c21575b20d4d"

workers_dev = true
route = ""
zone_id = ""

compatibility_date = "2021-11-19"

# Controls how long Cloudflare should cache each tile before requesting again
# from Strava.
#
# Use "0" to disable caching.
vars = { TILE_CACHE_SECS = "86400" }

# [secrets]
# STRAVA_ID
# STRAVA_COOKIES
