name = "strava-heatmap-proxy"
type = "webpack"

# Change this to your own account ID
account_id = "32100188be477c016941c21575b20d4d"

workers_dev = true
route = ""
zone_id = ""

compatibility_date = "2021-11-19"

# TILE_CACHE_SECS: Controls how long Cloudflare should cache each tile before
# requesting again from Strava. Use "0" to disable caching.
#
# ALLOWED_HOSTS: Sets CORS header and checks that requests have appropriate
# origins. If unset all hosts are allowed
vars = { TILE_CACHE_SECS = "86400", ALLOWED_HOSTS = "" }

# [secrets]
# STRAVA_ID
# STRAVA_COOKIES
